name = "JuliaFRG"
uuid = "19cab0c4-4f86-4eef-aea1-cf3716c4fad4"
repo = "https://gitlabph.physik.fu-berlin.de/julia-frg/JuliaFRGRegistry.git"
description = "Julia FRG registry"

[packages]
053fb7f8-31b7-4f68-aef8-4452b415dd8c = { name = "SpinFRGLattices", path = "S/SpinFRGLattices" }
37d616f8-0bcb-4e18-9a76-f5d18f52650d = { name = "PMFRG", path = "P/PMFRG" }
