name = "JuliaFRG"
uuid = "19cab0c4-4f86-4eef-aea1-cf3716c4fad4"
repo = "https://gitlabph.physik.fu-berlin.de/julia-frg/JuliaFRGRegistry.git"
description = "Julia FRG registry"

[packages]
053fb7f8-31b7-4f68-aef8-4452b415dd8c = { name = "SpinFRGLattices", path = "S/SpinFRGLattices" }
0e1bda0b-f6c0-498b-8522-61e6152bcfb4 = { name = "FRGLatticePlotting", path = "F/FRGLatticePlotting" }
2867bddc-101e-43c9-836d-7ce2d0afa337 = { name = "HDF5Helpers", path = "H/HDF5Helpers" }
37d616f8-0bcb-4e18-9a76-f5d18f52650d = { name = "PMFRG", path = "P/PMFRG" }
a44b592b-45f7-4b02-a4df-e53b23f0d903 = { name = "FRGLatticeEvaluation", path = "F/FRGLatticeEvaluation" }
b5390414-b2a3-41bc-a8fb-ec6971fc6e70 = { name = "PFFRG", path = "P/PFFRG" }
